### ISSUE TITLE
Readability of README

### ISSUE THREAD

**Issue by Smarre** [jasonroelofs/rice#100]
Hi,

I just want to drop in a suggestion to convert the README to Markdown file. Doxygen supports nowadays Markdown, so it would be possible to generate the README to the documentation using Markdown, which would automatically cause Github to render the README properly.

If someone wants to merge this suggestion, I can do the conversion :)

**Comment by jasonroelofs** [comment]
Doxygen supporting Markdown makes this more appealing for sure. If you want to take that on I'd be happy to check it out!

**Comment by Smarre** [comment]
I pushed a pull request: https://github.com/jasonroelofs/rice/pull/102

**Comment by Smarre** [comment]
The pull request was merged, so this can be closed :)
