### ISSUE TITLE
rb_frame_method_id_and_class will be deprecated from Ruby 2.5

### ISSUE THREAD

**Issue by k0kubun** [jasonroelofs/rice#105]
The API is used in https://github.com/jasonroelofs/rice/blob/2.1.2/rice/detail/method_data.cpp#L19, and will be deprecated from Ruby 2.5 https://github.com/ruby/ruby/commit/b6946d31fc201f6e6a5e046d58b69fa377bb76af.

**Comment by jasonroelofs** [comment]
Thanks for the report. I had noticed failures on Travis but hadn't dived too deeply into them yet.

Looking at https://github.com/ruby/ruby/commit/857827e3eed915543ac9d4d2541179ea4ded8eee, is switching to rb_ec_frame_method_id_and_class the expected way to go for this functionality?

**Comment by k0kubun** [comment]
I guess so, but unfortunately currently no direction seems officially fixed and the API is not exported yet. 

The API's actual removal should come with its replacement. So let's close this for now until the new API is fixed. Sorry for early notification.

**Comment by paddor** [comment]
Any updates on this? I've been trying to test one of our more resource hungry applications using the preview versions of Ruby 2.6 but it's impossible because of these deprecation errors. Is there a workaround?

**Comment by jasonroelofs** [comment]
I have yet to see any indication of a replacement for this API. Not sure if I'm looking in the wrong place or not. @k0kubun are there any updates here that you're aware of?

**Comment by k0kubun** [comment]
As far as I know, there's no update. Could you ping @ko1 or file a ticket to https://bugs.ruby-lang.org ?

**Comment by paddor** [comment]
Reported in https://bugs.ruby-lang.org/issues/15300

**Comment by paddor** [comment]
I just noticed that this works great under Ruby 2.6.2 :tada:
