### ISSUE TITLE
Mac OS: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by liepauls** [jasonroelofs/rice#111]
Hey, thanks for the awesome gem!

I managed to install the gem on ubuntu with no issues, however on mac OS (mojave) I'm getting errors while compiling:

```
$ gem install rice -v '2.1.3'
Building native extensions. This could take a while...
ERROR:  Error installing rice:
  ERROR: Failed to build gem native extension.

...

ld: warning: ignoring file ../rice/librice.a, file was built for archive which is not the architecture being linked (x86_64): ../rice/librice.a
Undefined symbols for architecture x86_64:

...

  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [unittest] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/user/.rvm/gems/ruby-2.5.1/gems/rice-2.1.3 for inspection.
Results logged to /Users/user/.rvm/gems/ruby-2.5.1/extensions/x86_64-darwin-17/2.5.0/rice-2.1.3/gem_make.out
```

Full output here - https://pastebin.com/raw/u3UDkbnj

Let me know if any additional info is required and thanks for your time.

**Comment by jasonroelofs** [comment]
I'm not sure what's going on here. I am also on Mojave and haven't seen this error before. The file `librice.a` is built as part of the `gem install` process so it seems that something related to your build environment is acting differently than mine.

The only difference I can find in your output vs mine is:

```
ar: `u' modifier ignored since `D' is the default (see `U')
```

Which implies that you have a newer / different version of `ar`?

**Comment by liepauls** [comment]
Alright, first I got rid of that warning, but the problem was still there.
After some googling I stumbled on https://github.com/tpoechtrager/osxcross/issues/11#issuecomment-39827659

I guess I had installed `binutils` (which includes `AR`) at some point, I uninstalled it and the gem installed successfully. Thanks!

**Comment by jasonroelofs** [comment]
Cool, glad you were able to figure it out!
