### ISSUE TITLE
Exception unit test failing

### ISSUE THREAD

**Issue by ogrant** [jasonroelofs/rice#117]
Hi,

First of all, thank you, love the library, it's very useful.

I am encountering an issue when running the unit tests:

  ...
  To_From_Ruby:array_to_ruby .
  To_From_Ruby:array_from_ruby .
  To_From_Ruby:hash_to_ruby .
  To_From_Ruby:hash_from_ruby .
  
  243 test(s), 629 assertion(s), 0 error(s), 1 failure(s)
  
  Failures:
  Exception:what: Assertion failed: foo != ex.what() (foo != s@ø©^?) at test_Exception.cpp:45
  FAIL unittest (exit status: 1)

I'm building this with the following:

clang++ --version
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

If you need any more information, let me know.

Thxs,

O.

**Comment by jasonroelofs** [comment]
That is a really weird failure. I haven't upgraded to Catalina yet, and cannot reproduce this failure on Mojave, but that error message implies that there's some memory corruption going on somewhere. Strange. It's probably about time to do the upgrade so when I get a chance to try this again I'll let you know.

**Comment by ogrant** [comment]
Hi. Any luck trying to reproduce that error? Thanks

**Comment by jasonroelofs** [comment]
Sorry, I haven't. This one kind of fell off my radar. I do have access to Catalina, just need to get some things set up to test this out.

**Comment by ankane** [comment]
fwiw, the test passes for me on Catalina, but I'm seeing similar behavior (random characters in error messages) with one of my gems on Travis CI.

https://travis-ci.org/github/ankane/torch.rb/builds/729531003

Changing calls from `throw Exception(...)` to `rb_raise(...)` fixes it (my C++ isn't great, so I may be doing something wrong).

**Comment by jasonroelofs** [comment]
I finally found a way to reproduce this... Windows! https://github.com/jasonroelofs/rice/pull/139/checks. Seeing what I can track down.

**Comment by jasonroelofs** [comment]
So the issue is that in some systems and situations we're not properly allocating the right size buffer (or not using the right functions) for the printf-formatted exception message. As it's reliably happening on Windows, and as some here are seeing in Mac, there should be a better way to do this that works on all platforms.

**Comment by ogrant** [comment]
Great news! Thanks! Can I ask you to create a new tag (2.2.1 maybe ?)

**Comment by jasonroelofs** [comment]
I plan on having a bigger release out in the next week or so, though that release will require at least C++14. Let me know if that won't work and I can look at also keeping a 2.x branch for such fixes.
