### ISSUE TITLE
Installation fails with Ruby 2.7

### ISSUE THREAD

**Issue by ankane** [jasonroelofs/rice#119]
It looks like a change with Ruby 2.7 breaks installation. Relevant part of error message:

```txt
detail/method_data.cpp:82:7: error: non-type template argument of type 'int' is not an integral constant expression
      arity);
      ^~~~~
/Users/andrew/.rbenv/versions/2.7.0/include/ruby-2.7.0/ruby/ruby.h:2777:60: note: expanded from macro 'rb_define_method'
#define rb_define_method(m, n, f, a) rb_define_method_tmpl<a>::define(m, n, f)
                                                           ^
detail/method_data.cpp:82:7: note: read of non-const variable 'arity' is not allowed in a constant expression
detail/method_data.cpp:62:54: note: declared here
    VALUE klass, ID id, VALUE (*cfunc)(ANYARGS), int arity, VALUE data)
                                                     ^
1 error generated.
```

**Comment by jasonroelofs** [comment]
Sure enough, thanks for the report. I'll see what I can track down.

**Comment by jasonroelofs** [comment]
Looks like Ruby 2.7 has turned `rb_define_method` into a templated macro when compiled under C++. Need to see how we can get access to the non-templated version of that method, as the location of this error is not itself a template and thus we can't Just Use the new stuff.

**Comment by jasonroelofs** [comment]
Yeah, this is looking like a bigger deal than I thought. I can't find a way to call the real `rb_define_method` C function when compiling under C++. Reaching out to some places to see if I can find some answers.

**Comment by ankane** [comment]
Thanks @jasonroelofs. You've probably already seen this, but looks like the change was made in https://github.com/ruby/ruby/pull/2461.

**Comment by jasonroelofs** [comment]
I had found the commits but didn't see the PR until now, thanks for the link.

**Comment by jasonroelofs** [comment]
I've filed a bug with the Ruby team about this. https://bugs.ruby-lang.org/issues/16480

**Comment by ankane** [comment]
Awesome, looks like it's been acked

**Comment by jasonroelofs** [comment]
Fix has been merged into `master` (via #122). I'll look at doing a release tomorrow.

**Comment by jasonroelofs** [comment]
Ok, Rice 2.2.0 has been released with this fix and other recent changes, and this issue should be done!

**Comment by ankane** [comment]
Thanks @jasonroelofs, works great!
