### ISSUE TITLE
How to prevent double free error

### ISSUE THREAD

**Issue by ankane** [jasonroelofs/rice#124]
Hey @jasonroelofs, I'm running into a `SignalException: SIGABRT` error in [or-tools](https://github.com/ankane/or-tools) when Ruby exits after a [specific method](https://github.com/ankane/or-tools/blob/92441630d67f4580f53331ba804840de340391c1/ext/or-tools/ext.cpp#L92) is called that returns an instance of a class wrapped by Rice.

On Linux: `double free or corruption (fasttop)`
On Mac: `pointer being freed was not allocated`

When the method runs but doesn't return the instance (like returning its address in memory instead), there isn't an error.

```c++
.define_method(
  "num_var",
  *[](MPSolver& self, double lb, double ub, const std::string& name) {
    // MPVariable is wrapped with:
    // define_class_under<MPVariable>(rb_mORTools, "MPVariable");
    MPVariable* var = self.MakeNumVar(lb, ub, name);

    // return var; // error
    return (uint64) &var; // no error
  })
```

This leads me to suspect that Ruby and the library are both freeing the object. Is there a way to tell Rice not to do this? I think this may be related to https://github.com/jasonroelofs/rice/issues/96.

**Comment by ankane** [comment]
Spoke too soon. Figure it out in https://github.com/ankane/or-tools/commit/2511996e624a21161c6868ec5a536b513ab91f11 based on #96.

Sorry for the bother!

**Comment by jasonroelofs** [comment]
Gotcha, glad you were able to track that down. Managing ownership of objects across C++ / Ruby boundaries is not trivial. Might be something worth making clearer in the documentation.
