### ISSUE TITLE
Exception_Handler Question

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#132]
Module and the auto function wrappers treat Exception_Handler as Data_Object<Exception_Handler>.  However, this introduces a circular reference:

Data_Type -> Module -> Module_Base -> Exception_Handler -> Data_Object -> Data_Type

Thus there is a Data_Type_fwd.hpp file which breaks this dependency. That works on GCC, but on MSVC it breaks because in Data_Object line 102:

      Data_Type<U> const & klass = Data_Type<T>::klass());

Since Data_Object only knows about the forward declaration of Data_Type, Data_Type<T>::klass() does not compile.

Of course I understand supporting MSVC is not important, but it did make me look at Exception_Handler and wonder why its wrapped as a Data_Object. It doesn't appear to be used in Ruby. As far as I can see, its wrapped simply to have Ruby manage its memory via registering the address of its wrapper object in the Ruby VM. Is this correct or am I missing something?

If that is in fact true, I would like to remove the Data_Object<T> wrapper and thus break the circular dependency (I realize its not the only one). Its lifetime instead would be managed in C++ by using std::unique_ptr<Exception_Handler>.

Thoughts?

**Comment by jasonroelofs** [comment]
It's been a while since I took a look at the exception side of things but you're probably right. I'll look closer to see if I can come up with a reason why not to do this but feel free to give it a try.

**Comment by cfis** [comment]
This has been completed.
