### ISSUE TITLE
Wrapped_Function Storage?

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#143]
Rice stores Wrapped_Function C++ objects as hidden attributes on the appropriate Ruby class. To do this requires wrapping the Wrapped_Function as a Ruby class using Data_Object thus exposing it to the Ruby garbage collector.

An alternative, C++ only solution, would be to have a Wrapped_Function_Table defined something like this:

std::unordered_map<VALUE, std::unordered_map<ID, std::unique_ptr<Wrapped_Function>>;

Where VALUE is the Ruby class identifier and ID is the method identifier. This would be a global data structure, so making i thread safe should be considered.

The upside of this solution is avoiding having to wrap Wrapped_Function in a Ruby object and then paying whatever overhead penalty that brings with the Ruby GC. It is also might be debatably more clear what is going on (note the comments in the existing code are wrong about how this works - they discuss hijacking Ruby's method alias system which is *not* what is happening from what I see).

**Comment by jasonroelofs** [comment]
I will note that how Rice actually hooks into Ruby is some of the oldest code in the library and honestly not something I've entirely understood (most of the comments are mine in an attempt to understand what's going on, and they probably are wrong in some detail). I've never understood if it was necessary for the methods to be stored on Ruby objects, but I imagine that hooking into Ruby's GC was probably one reason it was done this way.

I think your idea is worth a try. Rice also makes use of a method, `rb_frame_method_id_and_class` that the Ruby team has been trying to deprecate, and if your storage idea would remove our need for this functionality then lets give it a shot.

**Comment by cfis** [comment]
My idea would still require `rb_frame_method_id_and_class`  - ruby-prof has the same issue of needing to call that method. I doubt the Ruby team can get rid of it. There is probably some way to workaround that using a lambda and capturing the method id...but figure that can be done if that method is ever removed.

**Comment by cfis** [comment]
This has been done.
