### ISSUE TITLE
Which class deals with callback?

### ISSUE THREAD

**Issue by TelephonyMan** [jasonroelofs/rice#144]
I need the ability to call Ruby functions from the C++ module, using callback functions. So I am looking for ways to registering a callback function from Ruby, and then invoke them from the C++ module in a thread safe way.

The documentation says "**Rice provides a handful of convenience classes for dealing with callbacks.**"

But I am not able to locate any such classes that implement callbacks.

**Comment by jasonroelofs** [comment]
Good question. It's not straight forward to do this but it also depends on exactly what you're trying to accomplish. If you want cross-language polymorphism to work (subclass a C++ class in Ruby), that's what `Director` is for.

If instead you want to register a Ruby block into C++ that the C++ layer then calls later, you'll need to build an intermediary layer to accomplish this. For example, if you want the Ruby to look like this:

```ruby
exported_obj.register_block do
   puts "Called from C++"
end
```

Then you'll need to write a special function that's wrapped as `register_block` that holds the block:

```
// For the sake of discussion
Rice::Object registeredBlock;

void registerRubyBlock(Rice::Object block) {
  registeredBlock = block;
}

// then register the function:
define_method("register_block", &registerRubyBlock);
```

Then in your C++ you'll need another wrapper that can grab the stored block and call it directly:

```
void callRegisteredRubyBlock() {
    // Trigger Block#call on the stored block.
    registeredBlock.call("call");
}
```

Does that help? If not, please provide more details on what you're trying to accomplish and we can figure out something more specific to your use case.

**Comment by TelephonyMan** [comment]
Thanks for the quick response. I think I can best explain my requirement by showing how I have done the same using pybind11 for calling python functions from C++.

**The C++ code using pybind11**
```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;
namespace pylit = pybind11::literals;

class CPostmaster
{
public:
	CPostmaster(const std::string& modName)
	{
		PyEval_InitThreads();
	}

	void setCallBackOnEvent(py::object callable) { _cbEvent = callable; }
	void sendMessage(const std::string& messageData) { sendMessageStr(messageData); }
        void OnEvent(std::string message)
        {
		PyGILState_STATE state = PyGILState_Ensure();
		py::object result = _cbEvent(message.str());
		PyGILState_Release(state);
        }

private:
	py::object _cbEvent;
};

PYBIND11_MODULE(Postmaster, m)
{
	m.doc() = "Postmaster is a C++ module for exchanging messages between C++ and Python";
	py::class_<CPostmaster> postmaster(m, "Post");
	hive.def(py::init<const std::string&>())
		.def("SetCallBackOnEvent", &CEpiHive::setCallBackOnEvent)
		.def("SendMessage", &CEpiHive::sendMessage);
}
```
**The Python Code to interact with C++ extension**
```
import Postmaster
import time

post = Postmaster.Post("Test")

def onEvent(message):
    print(message)

def main():
    post.SetCallBackOnEvent(onEvent)
    post.SendMessage("Hello")
    time.sleep(10)

main()
```
As you can see, the python code registers a callback. It sends a message and waits for the reply. When the OnEvent() invoked on the C++ side, it acquires the GIL, calls the callback function and then releases the GIL. GIL is Global Interpreter Lock. That ensures no thread related violations occur. 

You have given me the code to register and call the callback function, thanks again for that. What about thread safety? How do I lock and release the interpreter? Is it not necessary in Ruby?

**Comment by TelephonyMan** [comment]
I implemented a sample C++ extension using Rice. But it is not working. When I call the callback function, it says "stack level too deep".

**C++ Code**
```
class CPostmaster
{
public:
	CPostmaster(const std::string& modName) : _name(modName), _work(_ioService)
	{
		int noOfCores = boost::thread::hardware_concurrency();
		for (int i = 0; i < noOfCores; i++)
		{
			_threadPool.create_thread(boost::bind(&boost::asio::io_service::run, &_ioService));
		}
	}

	void setCallBackOnEvent(Rice::Object callable) { _cbEvent = callable; }
	void sendMessage(std::string message) 
	{ 
		auto timer = boost::make_shared<boost::asio::deadline_timer>(_ioService, boost::posix_time::seconds(1));
		timer->async_wait(boost::bind(&CPostmaster::OnEvent, this, timer, message));
		std::cout << "Event scheduled" << std::endl;
	}

	void OnEvent(boost::shared_ptr<boost::asio::deadline_timer> timer, std::string message)
	{
		std::cout << "OnEvent called" << std::endl;
		_ioService.stop();
		if(_cbEvent.is_nil()) 
		{
			std::cout << "Callback not Initialized" << std::endl;
		}
		else
		{
			try
			{
				_cbEvent.call("call","Reply to " + message);
			}
			catch(const Rice::Exception& e)
			{
				std::cerr << e.message() << '\n';
			}
		}
	}

private:
	std::string _name;
	Rice::Object _cbEvent;
	boost::asio::io_service _ioService;
	boost::asio::io_service::work _work;
	boost::thread_group _threadPool;
};

extern "C"
void Init_Postmaster()
{
	Rice::Class test =
        Rice::define_class<CPostmaster>("Post")
		.define_constructor(Rice::Constructor<CPostmaster,std::string>())
		.define_method("SendMessage", &CPostmaster::sendMessage)
		.define_method("SetCallBackOnEvent", &CPostmaster::setCallBackOnEvent);
}


```
**The Ruby script**
```
require 'Postmaster.so';

def onEvent(message)
    puts message;
end 

class Postmaster
    def initialize(name)
        @post = Post.new name
        @post.SetCallBackOnEvent method(:onEvent)
        @post.SendMessage "Hello"
    end
end

obj = Postmaster.new "Test"
sleep 5
```
The output I get is as follows:
ruby test.rb
Event scheduled
OnEvent called
stack level too deep

**Comment by jasonroelofs** [comment]
I will throw together a working example to make sure my ideas are right, but one thing to understand with Ruby threads is that Ruby's runtime was not designed to be run in a multi-threaded situation, and thus does not have the same protections that Python does. I'm not sure how this is changing with Ruby 3, but up until now Ruby does not work well across threads, so you will want to make sure that whatever thread you initialize Ruby on is the same thread you make Rice calls.

**Comment by TelephonyMan** [comment]
Thanks, looking forward to your example. I'll deal with the threading problem carefully.

**Comment by jasonroelofs** [comment]
I've added a new sample showing this callback pattern (https://github.com/jasonroelofs/rice/tree/master/sample/callbacks) that seems to do exactly what you have and from what I can see works fine. To make sure it's not the threading making Ruby confused, can you try your code without the threads? Or if you see a difference between your code and mine, please point it out!

**Comment by TelephonyMan** [comment]
Sorry, I didn't realized you had replied. 

Hmm, it is working for you because you are invoking the callback from ruby. But my use case is different. My C++ module is used for asynchronous messaging with components in other machines. After the initialization, the module waits on a socket to receive messages from the other side.  When the event is received, the callback function will be invoked. That thread will be different than the thread on which ruby code will be running. That is why I run into problems.

So, how did I solve this problem in node.js, which has a similar single threaded framework?

The solution is as described in [this medium post](https://medium.com/@gx578007/notes-of-nodejs-addons-message-handlers-399476c07888). Is something similar possible in Ruby?

**Comment by TelephonyMan** [comment]
The libuv library came as part of the node-gyp in case of nodejs. May be I will try using libuv independently with my C++ module to achieve the same result. I'll share the results here if it works.

**Comment by jasonroelofs** [comment]
Gotcha, that makes sense. Yeah only two thoughts come to mind. First, somehow set up a message bus to a dedicated thread that runs the Ruby VM (evented, thread-safe queue, etc) to make sure Ruby calls only happen on that thread. Second would be a bigger split between C++ and Ruby. Instead of the C++ calling directly into Ruby, it could instead put the message on another socket shared with a Ruby process. This would be more complex to set up to make sure the communication was solid between the two processes but could be easier to maintain and guarantee thread safety.

**Comment by cfis** [comment]
These posts might be helpful:

https://stackoverflow.com/a/53671988
https://silverhammermba.github.io/emberb/c/#threading

Basically you can create a new ruby thread from the extension and then use it to invoke the callback.

And a queue approach like @jasonroelofs  mentioned:

https://www.burgestrand.se/articles/asynchronous-callbacks-in-ruby-c-extensions/
