### ISSUE TITLE
Null objects are wrapped as valid ruby object instead of nil

### ISSUE THREAD

**Issue by cyrilleberger** [jasonroelofs/rice#145]
Imagine you wrap the following function:

```c++
struct Foo
{
  Foo* a() { return nullptr; }
};
```
I would expect when calling `Foo.new().a()` in Ruby to get a `nil` value, but instead, I get a valid ruby object, and then doing anything with that object would crash.

I solved that by doing this:

```c++
template<>
inline Rice::Object to_ruby<Foo*>(Foo* const & x)
{
  if(x)
  {
    return Rice::detail::to_ruby_<Foo*>::convert(x);
  } else {
    return Rice::Object();
  }
}
```

But I would expect this to be the standard behavior. If you agree, I can make a pull request with the change.

**Comment by jasonroelofs** [comment]
A crash is definitely a bug in Rice. I'm kind of surprised this hasn't come up before! I agree a NULL in C++ should swap to a `NilClass` in Ruby. Happy to review a PR fixing this bug.

**Comment by cfis** [comment]
I can duplicate this issue and fixed it in my branch. Note that this was broken in both directions. So returning nullptrs to Ruby as well as passing nil to C++.
