### ISSUE TITLE
Basic STL Support

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#148]
Since STL is such an integral part of C++ programs, it would be good for Rice to have some sort of support for STL out of the box. In particular I'm thinking about containers such as std::vector and std::map. Nice to have's would be tuples and optionals.

**Comment by jasonroelofs** [comment]
Agreed, some of the more commonly used structures would be great to have.

**Comment by ankane** [comment]
This would be great. Many of the custom type conversions in #149 are for `std::vector` of a common type like `int`, `float`, `std::string`, etc.

Here's a good example: https://github.com/ankane/datasketches/blob/23a66608fa915fc798b7264ebf23c5d2e97e56ca/ext/datasketches/kll_wrapper.cpp#L9-L91

**Comment by cfis** [comment]
Added support for std::unique_ptr and std::smart_ptr in 25d820fa1daf46fdaad3d223c51382cbcba79ef1.

**Comment by cfis** [comment]
Ok, I have added in a first cut of std::vector support. I also added std::optional and std::complex support. I then moved std::string into the stl folder.

**Comment by cfis** [comment]
@ankane @jasonroelofs  - See what you think of how implemented std::vector support. Rice automatically handles vectors and registers them as classes under Rice::Vector in Ruby. For example:

std::vector<int32_t> -> Rice::Vector::Int
std::vector<uint32_t> -> Rice::Vector::UnsignedInt

Etc. The class name is derived from typeid(std::vector<T>::value_type) and then I have some code that uses the demangled name and makes Ruby appropriate class names.

You can also do this manually if you prefer. `define_vector<std::vector<int>>("IntVector")` as with wrapping other C++ classes.

I've made vectors act like Ruby Arrays. For example, return nil if out of bounds versus an exception, etc. So I think the basics are good, but there would be a fair bit more of work to fully map the Ruby Array api to them. For example, `array.push(1)` works, but `array.push(1, 2, 3)` does not because I haven't yet added support for any random number of arguments.

If this path looks good, then I think the other containers worth wrapping are std::map, std::unordered_map, std::set, std::unordered_set, in that order. But its pretty time consuming, doing vector took me about a week. Additional containers would be faster since it did take me a while to figure out how to do vector and make necessary changes in Rice.

And if either of you want to wrap these other containers - please feel free to do so! Let's just make sure not to duplicate work.

**Comment by cfis** [comment]
@ankane brought up a point I've been wondering about.

Do we want a separate include for stl support - which is what I did in the latest set of changes. Meaning now:

```cpp
#include <rice/rice.hpp>
#include <rice/stl.hpp>
```

Pybind does it this way, and it made sense to me. I don't remember if you need that 2nd include for std::string support with pybind or not.

std::string is so commonly used, I can see the argument that it should be included in the main header. But then I could make the same argument about std::vector. Which led me the conclusion maybe it should be all or nothing. For now I went with the nothing approach (you have to manually include stl) but I'm fine wit the all approach (just have one rice.hpp header).

Comments?

**Comment by jasonroelofs** [comment]
I can't say I have any preference one way or the other, but to have picked something I feel that having the two includes is the way to go. It can be added if people want the container support.

**Comment by cfis** [comment]
I'm going to consider basic support done. We can add separate tickets for each additional type we want to add (map, unordered_map, etc).
