### ISSUE TITLE
Ownership Rules

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#150]
In previous versions of Rice, ownership rules were:

- C++ objects constructed by Rice were owned by Rice
- Pointers passed to Rice were owned by Rice
- References passed to Rice were copied by Rice
- Values passed to Rice were copied by Rice

With recent changes,  you can now specify if Rice should take ownership of passed values or not. This is documented at https://github.com/jasonroelofs/rice/blob/master/README.md#ownership.

Currently, the defaults are that Rice takes ownership of pointers and references. After working with this for the last week I think this is a bad idea and the default should be the opposite. Thus by default, Rice should not take ownership of pointers and references. Instead it should store them. The one exception being if Rice constructs a C++ object then it owns it.

My change of heart is due to reading up a bunch of style guides. In modern c++, best practices are that parameters passed or returned by pointer/reference do *not* transfer ownership. Instead, transferring of ownership should be done via the use of smart pointers.

Here are some references:

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-raw
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-smartptrparam
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-unique_ptr
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-shared_ptr
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-smartptrparam
https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers
https://chromium.googlesource.com/chromium/src/+/master/styleguide/c++/c++.md#object-ownership-and-calling-conventions

Unless there are objections, I plan on making this change.

**Comment by jasonroelofs** [comment]
This all makes sense, and now is the best time to look at changing these rules.

👍

**Comment by cfis** [comment]
This is done. I updated the api so that if you want to specify ownership, now you do:

```cpp
   define_function("create", &Factory::create, Return().takeOwnership());
```
