### ISSUE TITLE
Documentation for 4.x

### ISSUE THREAD

**Issue by jasonroelofs** [jasonroelofs/rice#152]
Opening an issue to have a place of discussion for Rice's documentation. I've just set up a versioned structure so we now have https://jasonroelofs.com/rice/3.x/ and https://jasonroelofs.com/rice/4.x/ and https://jasonroelofs.com/rice/ currently redirects to `3.x`, which we'll switch when `4.x` is released.

There are a few backwards incompatible changes and some new API methods that need to get into the README. The things that need to be documented yet (possibly incomplete):

- [ ] Migration from `to_ruby`/`from_ruby` to the new struct.
- [ ] `define_function` / `define_singleton_function` vs `define_method` / `define_singleton_method` and `self`
- [x] `Return().takeOwnership()` and ownership rules
- [ ] `Arg.keepAlive`
- [ ] `stl.hpp` and the caveats of STL support.

I'm also open to thoughts on using other ways of documenting this library than Doxygen. Did some searching and there doesn't seem to be a lot of other options, either Doxygen or sphinx (which then requires Python). Similarly the single-page can be a bit cumbersome but I don't want to hide important docs in the code itself, as a lot of what Rice exposes isn't very discoverable on its own.

**Comment by cfis** [comment]
Cool. Note I have been updating the documentation as I have been making changes. What's done is:

* define_function/define_method
* take_ownership
* keepalive

I was planning on writing a Migration section based on the changes Andrew has been tracking. And of course an stl section.

**Comment by cfis** [comment]
@jasonroelofs - the other thing I ponder..what do you think about moving to a documentation formation more along the lines of how PyBind does it? So a bunch of shorter pages with a table of contents. As our readme files get bigger, it starts to get a bit overwhelming.

**Comment by jasonroelofs** [comment]
Yeah, we should do something more searchable and manageable, though not sure what yet. Do you have any preferences?

**Comment by cfis** [comment]
No preference. I was thinking of looking at sphinx since that seems to be popular these days in the Python world and looks nice.

**Comment by KirisameMarisas** [comment]
I downloaded from gem , but the latest version is 3.0.0.
Does 4.x not push on rubygem.org?

**Comment by jasonroelofs** [comment]
@KirisameMarisas Sorry for the confusion, yeah the docs do say 4.0 but there isn't an actual release for that version yet. I probably should make sure that's clear.

**Comment by jasonroelofs** [comment]
Closing this ticket, lets continue this discussion in PR #158.
