### ISSUE TITLE
When returning self return the same ruby object

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#154]
One thing that dawned on me when adding stl support (#148), is that methods that return self do not return the same Ruby object. For example:

```ruby
vector = IntVector.new
vector << 1 << 2 << 3
vector.size == 1 (what!)
```
I was expecting to get a vector back with three elements but got back one. Digging in, I realized there are two different issues.
This is the code:

```cpp
define_vector<std::vector<int32_t>>().
  define_method("<<", [](std::vector<int32_t>& self, int32_t value)
  {
    self.push_back(value);
    return self;  <------  Returns by *value* - oops
  });
```
Problem #1 - the method returns by value, making 3 different copies of the vector. That is fixable by specifying the lambda return type like this:

```cpp
[](std::vector<int32_t>& self, int32_t value) -> &std::vector<int32_t>&
```

Problem #2 - Every time a C++ object is returned we wrap it in a new Ruby object. So although the Ruby code above now works, there are 3 Ruby objects pointing to the same vector. Most of the time that is probably ok, but its surprising and not good for performance. And I suppose it could break some code that happens to extend that one object.

In the general I don't think its worth Rice keeping track of every C++ object to always return the same Ruby object. That would require a global unordered_map that really should be protected by mutexes to be thread safe.

I do however think its worth fixing the special case of returning self since that can be checked immediately after calling the C++ method and involves no global tracking or locking.

**Comment by jasonroelofs** [comment]
This all makes sense, and the commit is clear enough, particularly with the tests. Is there another change you want to make regarding this edge case?

**Comment by cfis** [comment]
This was a far as I was going to take it. From reading the pybind documentation, it looks like pybind does return the same python object for the same c++ object. But like I wrote above, I'm not sure its worth doing. Thoughts?

**Comment by jasonroelofs** [comment]
Right, I'd like to see a problem such a mapping would solve before diving into that. What we've got now is probably fine.
