### ISSUE TITLE
Rethinking From_Ruby

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#160]
I haven't been happy with how From_Ruby is implemented and when trying to add code to convert Ruby Array's to std::vector's I realized the current system won't support vector references or pointers.

The fundamental issue is native functions that take types that need to be copied between Ruby and C++ as references or pointers. For example, a function like this:

```cpp
void function(int& intRef, std::string* stringPointer)
```

Since the types are copied, you can't just implement From_Ruby<&int> because then the convert method returns a reference (or pointer) to a local object - resulting in a crash. That was the same problem with casts.

Types that are wrapped, and not copied, work fine. Specifically anything define via `define_class` or `define_enum` work correctly because the Ruby object is a T_DATA and thus stores the master copy of the instance so taking a reference or pointer is easy.

Thus a while back I added the concept of Builtin types (types that have to be copied) and the `NativeArg` template class which is specialized for Builtin types and external types. `NativeFunction` creates a `NativeArg` for each argument sent to a native function. `NativeArg` has a specialization for builtin types that has a member variable to store results from `From_Ruby` calls so that it becomes possible to pass references or pointers.

Unfortunately, this doesn't work for passing vectors that start as Ruby arrays:

```cpp
template<typename T>
struct From_Ruby<std::vector<T>&>
{
  std::vector& convert(VALUE value)
  {
    if (rb_type(value) == T_DATA)
    {
       // ok great this is a wrapped vector
       using Intrinsic_T = intrinsic_type<T>;
       return *Data_Object<Intrinsic_T>::from_ruby(value);
    }
    else if (rb_type(value) == T_ARRAY)
    {
      // ok now what? If we create a vector here and return it as a ref we get a crash
    }
  }
}
```
The current solution assumes that Builtin types can be determined at compile time. But in this case, you have to do a runtime check. VALUE could be a Ruby wrapper for a std::vector instance or it could be a Ruby Array. Its an Array, then it acts like a builtin type in that we have to copy data from Ruby to C++. But there is no place to store the vector we need to create.

Thus having a structure (From_Ruby) with static methods just doesn't cut it. We really need a class that you can create instances of that can maintain internal state that is determined partially at compile time but can be overriden at runtime.

One approach:

```cpp
template <typename T>
class FromRuby
{
  virtual T convert() = 0;
}

template <typename T>
class IntFromRuby: FromRuby<T>
{
   T convert(VALUE value)
   {
     this->value_ = rb_num2long_inline(value);
     if constexpr (std::is_pointer_v<T>)
     {
      return &this->value_;
     }
    else
    {
      return this->value;
   }
   }
private:
  using Intrinsic_T = instrinsic_type<T>;
  Intrinsic_T  value_;
};

template<typename T>
FromRuby* makeFromRuby;

template<> FromRuby* makeFromRuby<int>()
{
  return new IntFromRuby<int>();
}

template<> FromRuby* makeFromRuby<int&>()
{
  return new IntFromRuby<int&>();
}

template<> FromRuby* makeFromRuby<int*>()
{
  return new IntFromRuby<int*>();
}
```

You would want to add an intermediate class between `FromRuby` and `IntFromRuby` since most of its code would be the same for all Builtin types (numeric, boolean, string, null).

Note that I tried a similar pattern on the `Wrapper` class with an abstract base class that had a method with a return type defined by a typename. MSVC was fine with it, but g++ would throw exceptions that were finally fixed by having the base class return a void pointer (see f29b21f71def675a735b690d59519014927804dd). So this approach might not even be viable.

Anyway, I think we should probably resolve this before 4.0 since it would result in a big API change. FYI, To_Ruby has a similar issue which is knowing when Ruby should take ownership of an object or not. That was resolved by adding an isOwner parameter to the convert method, but having an instantiable class is another way of solving it.

A last thought. Having to create a wrapper object for each argument that is passed to a native function is annoying. It is how Rice now works (so no change there). In theory, when a NativeFunction is created it could create these wrapper objects and then just reuse them for every method call. I tried doing that one day and didn't succeed for reasons I don't remember, but that would be a good optimization to put in place.

**Comment by jasonroelofs** [comment]
Is this mainly an issue trying to make the standard library usage seemless between the two languages? I looked a bit more into how pybind11 handles the issue and from what I could find and understand, either they handle type conversions themselves (all of the basic types) or you have to build out a full object like you're suggesting here (https://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html).

This does seem like something that would be a significant change, is it possible to support both a static convert function that we have today, and a more fully fleshed out and instantiated object if that kind of tracking is required?

**Comment by cfis** [comment]
Its a general issue that I have spent the last few months trying to figure out a good solution. std::vector just showed me the solution I have isn't very good (I already knew that, but it really pointed it out).

This new approach so far looks better - its allows the removal of NativeArg class and avoids the overhead of having to create wrapper objects for every time we want to translate something to C++. And really the api isn't that different:

```cpp
From_Ruby<int>::convert(value);
From_Ruby<int>().convert(value);
```

This also seems like a better solution for To_Ruby and passing around ownership information.  

As far as pybind11 and the two ways it deals with STL containers - I think wrapping is clearly better than copying.  And if you really want copying its really easy to implement.

**Comment by jasonroelofs** [comment]
Understood, that makes sense, and yeah that isn't a huge change in syntax away from how much we're already changing. Sounds good to me.

**Comment by cfis** [comment]
I think this turned out pretty well - it solved existing issue and allowed the remove of NativeArg, NativeReturn and is_builtin structures. However, it did require writing a bunch more To_Ruby and From_Ruby template specializations for fundamental types (adding reference and pointer support). That code is very repetitive, but easy to understand, and there should be no need to have to update it in the future. Going to call this done.

**Comment by cfis** [comment]
FYI - the payoff:

doc/_build/html/stl/vector.html#array-to-vector

It describes being able pass a Ruby array to a method that takes a vector and for Rice to be able to automatically convert it while at the same time also being able to work with wrapped std::vectors too.
