### ISSUE TITLE
Publishing Docs

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#161]
@jasonroelofs  - Were you planning on automating the deployment of docs to https://jasonroelofs.com/rice/4.x ? Or should I be doing something after I update them and then build them locally using `rake doc`. Should there be  a `rake publish_doc` or something?

**Comment by jasonroelofs** [comment]
I need to look at how that can be automated. It should be, given the docs are hosted on GitHub Pages (and thus just need to update the `gh-pages` branch), it should be something GitHub Actions should be able to do. I'll take a look, but for now I'll get the current state of the docs deployed.

**Comment by jasonroelofs** [comment]
Docs are published at https://jasonroelofs.com/rice/4.x/introduction.html

When we push the 4.0 release, I'll update the redirect at https://jasonroelofs.com/rice to go there instead of 3.x.

**Comment by jasonroelofs** [comment]
I went ahead and pushed the redirect early, this issue is done.
