### ISSUE TITLE
Method Call Performance with Rice 4 and Ruby 3

### ISSUE THREAD

**Issue by ankane** [jasonroelofs/rice#162]
Hey, just noticed the test suite for OR-Tools runs about 4x slower with Rice 4/Ruby 3 than it does with Rice 4/Ruby 2.7, Rice 4/Ruby 2.6, and Rice 3/Ruby 3 ([CI link](https://github.com/ankane/or-tools/runs/2606610507?check_suite_focus=true)). It's the same on both Ubuntu and Mac (haven't tried Windows).

It looks to be due to method (and function) calls taking longer to run. There's a similar difference when benchmarking very simple methods (in a [fresh repo](https://github.com/ankane/rice_repro/)), like:

```cpp
Class rb_cHello = define_class("Hello");
rb_cHello.define_function("world", []() {
  return 123;
});
```

Any idea what it could be?

**Comment by ankane** [comment]
Ah, it looks like `-O2` is missing from `CXXFLAGS` in the Makefile for Ruby 3.

Ruby 3

```
CXXFLAGS = $(CCDLFLAGS)  -std=c++17 $(ARCH_FLAG)
```

Ruby 2.7

```
CXXFLAGS = $(CCDLFLAGS) -g -O2 -std=c++17 $(ARCH_FLAG)
```

**Comment by jasonroelofs** [comment]
Interesting. I don't think Rice itself sets those though, unless https://github.com/jasonroelofs/rice/blob/master/lib/mkmf-rice.rb#L99 possibly is missing `CXXFLAGS`?

**Comment by ankane** [comment]
Hmm, seeing a difference even without Rice (possibly related to https://bugs.ruby-lang.org/issues/17337).

```ruby
require 'mkmf'

p $CXXFLAGS # "-g -O2" for Ruby < 3, "" for Ruby 3

create_makefile('hello')
```

It looks like C extensions use `-O3` by default (`optflags = -O3` in Makefile). What do you think about adding `$CXXFLAGS += " $(optflags)"` to `mkmf-rice`?

**Comment by jasonroelofs** [comment]
I don't think that should be an issue? Can take a look.

**Comment by cfis** [comment]
So I usually manually build Ruby, and here is what I see:

Ruby 2.7:

```
$ ruby -rrbconfig -e "puts RbConfig::CONFIG['CXXFLAGS']"
-g -O2
```

Ruby 3.0:

`ruby -rrbconfig -e "puts RbConfig::CONFIG['CXXFLAGS']"`

So yeah, Ruby 3.0 by default doesn't seem to be setting CXXFLAGS.

For optflags, ruby 2.7 and 3.0:

```
$ruby -rrbconfig -e "puts RbConfig::CONFIG['optflags']"
-O3 -fno-omit-frame-pointer
```

However, Ruby's documentation does say:

> Some C compiler flags may be added by default depending on your environment. Specify optflags=.. and warnflags=.. as necessary to override them.

So...does should Rice just CXXFLAGS directly instead of copying from optflags?

**Comment by ankane** [comment]
It looks like a similar situation with Ruby 3.1 (with rbenv):

```text
$ ruby -rrbconfig -e "puts RbConfig::CONFIG['optflags']"
-O3 -fno-fast-math
$ ruby -rrbconfig -e "puts RbConfig::CONFIG['CXXFLAGS']"
-fdeclspec
```

I think it'd be nice for C++ extensions to have the same performance as C ones by default, but if not, developers can always add it manually. fwiw, I haven't had any reported issues from adding it to my projects.

**Comment by ankane** [comment]
Cleaning up stale issues
