### ISSUE TITLE
How to write `has_key?` in Rice?

### ISSUE THREAD

**Issue by kojix2** [jasonroelofs/rice#166]
Hello, Rice developers.

Thank you very much for making a great library to connect Ruby and C++. 
This is really useful.

I'm trying to write a tool to do UMap in Ruby.
https://github.com/kojix2/umap

I have a question. How to write `has_key?` or `key?` in Rice?

In the C API, it will be `rb_hash_has_key(VALUE hash, VALUE key)`, 
How to write it in Rice? 

I don't know much about C++, so I would appreciate any source code or hints.

**Comment by ankane** [comment]
Hey @kojix2, it looks like there's not currently a [Rice function](https://github.com/jasonroelofs/rice/blob/master/rice/cpp_api/Hash.hpp) for it, but you can use:

```cpp
hash.call("has_key?", key);
```

**Comment by kojix2** [comment]
Thanks! It worked.
And Thanks for making numo.hpp!
