### ISSUE TITLE
YARD documentation

### ISSUE THREAD

**Issue by uvlad7** [jasonroelofs/rice#172]
Is there any way to create YARD docs for classes and methods implemented with Rice? I mean, without having to create a new YARD plugin.

Sorry to bother you, but I couldn't find any information on this, or any issue mentioning documentation.

**Comment by Smarre** [comment]
Is writing the documentation manually not enough? That is, with `@!parse` or `@!method` or similar?

**Comment by uvlad7** [comment]
Oh, I'm sure it is, I just didn't know about this feature. Thank you for the quick response!

**Comment by uvlad7** [comment]
Well, I spent a lot of time to find that `@!parse` or `@!method` or similar directives don't work in c/cpp files. So, I end up creating a yard extension and reading [YARD issues](https://github.com/lsegal/yard/issues/1281) related to documenting native code.

May be someone will find [the result](https://github.com/uvlad7/ruby-jsoncons/blob/master/yard_extensions.rb) useful.
