### ISSUE TITLE
Poorly designed descendants can cause a segfault

### ISSUE THREAD

**Issue by uvlad7** [jasonroelofs/rice#173]
Please have a look [here](https://github.com/uvlad7/ruby-jsoncons/blob/master/test_descendant.rb). The problem is that if a class uses [define_constructor](https://github.com/uvlad7/ruby-jsoncons/blob/master/ext/jsoncons/jsoncons.cpp#L66), it relies on `initialize` to always being called, and if it doesn't, it will crash. And it's possible to mistakenly skip that call.
Yes, such a child is not an example of good program design, but I still believe it shouldn't be possible to cause a segfault from a bug in the Ruby world, not from ffi related stuff or from pure native code.
Stdlib classes are well-known as bad parents, but at least `Array` doesn't suffer from this problem. The [curl](https://github.com/taf2/curb/blob/master/ext/curb_easy.c#L3793) gem doesn't work in that case, but it doesn't segfault, it raises an exception.

**Comment by jasonroelofs** [comment]
Yeah this is a long standing issue that I'm not sure how best to fix. It might be possible to add an explicit check where the segfault happens (a null pointer reference) and instead throw an explicit exception? It will still crash as the object is unusable but at least that could give the user a message as to what happened.

**Comment by uvlad7** [comment]
I think checking and throwing an exception is the best possible solution, or at least a good enough solution. Such subclasses aren't supposed to work, they're just supposed not to blow the interpreter up with a segmentation fault.

**Comment by cfis** [comment]
Poorly designed is an unfair critique. Ruby has two methods involved in object creation. First is allocate and second is initialize. Allocate is a class method that is called with a single argument of type VALUE which is the Ruby class. There is no way for Rice to create a C++ object at that point - if the C++ class takes any constructor parameters they are not available.

The second method is an instance method, initialize, and takes a VALUE, the newly created Ruby object, plus any parameter to initialize the class. Thus only at this point can Rice instantiate a new C++ instance.

As a programmer if you create a new subclass, override initialize and do not call super, then that is simply wrong and invalid for any Ruby class.

I do agree that an exception should be thrown though and not crash the interpreter.

**Comment by uvlad7** [comment]
@jasonroelofs sorry for necroposting, but I found a similar [issue](https://github.com/matsadler/magnus/issues/67) in the Magnus repo and thought the [approach](https://github.com/matsadler/magnus/blob/663e70029fd493ee2548b333760d7cd57b1b9637/src/class.rs#L402) used there is interesting.

It calls `rb_define_alloc_func` with a function that creates a `Default` instance. So, allocation happens during the "allocate" call. And "initialize" just [sets](https://github.com/matsadler/magnus/blob/663e70029fd493ee2548b333760d7cd57b1b9637/examples/complete_object/ext/temperature/src/lib.rs#L39) fields. I'm not sure how it lines up with C++, but maybe it's possible to call default constructor - and handle `std::bad_alloc` - [here](https://github.com/jasonroelofs/rice/blob/37f58509ae05ee1791ba3a8636fd60fa812b5d21/include/rice/rice.hpp#L7932) and don't call `new` [here](https://github.com/jasonroelofs/rice/blob/37f58509ae05ee1791ba3a8636fd60fa812b5d21/include/rice/rice.hpp#L7963)?

It appears that it's not possible to redefine allocator registered with `rb_define_alloc_func` by simply redefining `allocate`:

<details>
  <summary>Show</summary>
 
```c
File: ruby/vm_method.c
1151: void
1152: rb_define_alloc_func(VALUE klass, VALUE (*func)(VALUE))
1153: {
1154:     Check_Type(klass, T_CLASS);
1155:     RCLASS_ALLOCATOR(klass) = func;
1156: }
1157: 
1158: void
1159: rb_undef_alloc_func(VALUE klass)
1160: {
1161:     rb_define_alloc_func(klass, UNDEF_ALLOC_FUNC);
1162: }
1163: 
1164: rb_alloc_func_t
1165: rb_get_alloc_func(VALUE klass)
1166: {
1167:     Check_Type(klass, T_CLASS);
1168: 
1169:     for (; klass; klass = RCLASS_SUPER(klass)) {
1170:         rb_alloc_func_t allocator = RCLASS_ALLOCATOR(klass);
1171:         if (allocator == UNDEF_ALLOC_FUNC) break;
1172:         if (allocator) return allocator;
1173:     }
1174:     return 0;
1175: }
```

```ruby
3.0.2 :001 > class T
3.0.2 :002 > end
 => nil 
3.0.2 :003 > T.allocate
 => #<T:0x000056286665a100> 
3.0.2 :004 > class T
3.0.2 :005 >   class << self
3.0.2 :006 >     def allocate
3.0.2 :007 >       p "allocate #{self}"
3.0.2 :008 >       super
3.0.2 :009 >     end
3.0.2 :010 >   end
3.0.2 :011 > end
 => :allocate 
3.0.2 :012 > T.allocate
"allocate T"
 => #<T:0x0000562866bcc4d0> 
3.0.2 :013 > T.new
 => #<T:0x0000562866d879f0> 
```
</details>

so it's a safer approach - even if `initialize` is not called, the object will still be valid, in it's default state, just like a pure Ruby implementation.

**Comment by jasonroelofs** [comment]
Interesting, thanks for the pointers. I don't plan on tackling this at the moment but will keep an eye on Magnus and use that if I feel this needs to be better handled.

**Comment by cfis** [comment]
Rice needs to set a customer alloc function via  rb_define_alloc_func so that Ruby creates objects of type T_DATA instead of the default of T_OBJECT. Thus the question then becomes whether the allocation function should be updated to both create the wrapper Ruby object and the underlying C++ object (which is now created in the initialize funciton as you mentioned). 

I agree with you that allocate should do both jobs - that would then let users implement whatever they want in an initialize function (although really there shouldn't be any need to do anything). I think that would be a workable change in Rice (have to think about inheritance a bit more). On the other hand, this doesn't seem particularly critical either - it is just protecting against something a programmer should never do anyway (override initializer and fail to call super).
