### ISSUE TITLE
Version 4.1

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#182]
@jasonroelofs I think I'm at a good stopping point for a 4.1 release if that works for you. Tests pass, docs updated, changelog updated.

Note I called this 4.1, but there are a couple breaking changes so I could see some logic in calling it 5.0. Breaking changes are:

* Rename Arg#isValue to Arg#setValue and then Arg#getIsValue to Arg#isValue (this may be a breaking change for some users)
* Rename Return#isValue to Return#setValue and Return#getIsValue to Return#isValue (this may be a breaking change for some users)

The fix is simple, and I would guess these methods are not used much.

**Comment by jasonroelofs** [comment]
Yeah, this all looks good, thanks for your work here! The renames I'm sure are fine and if there is someone who asks why the methods got renamed, we can re-add the older names as fallbacks. But yeah I doubt that is going to be an issue. And yeah 4.1 is a good version bump for this amount of changes.

**Comment by cfis** [comment]
I do now see  random failure on windows without gc.stress for the instance tracking feature (not really sure its related to gc.stress but it wasn't happening before). Will take a look.

**Comment by cfis** [comment]
Ok, took a look at this and can sporadically replicate it. I've been wondering if instance tracking is a good idea or not, and this makes me think it is not. Going to play with this a bit more.
