### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mvastola** [jasonroelofs/rice#187]
Hi,
First of all, thanks for this great gem. I just started playing with it, and if you don't mind I had a few minor nitpicks that came as I am trying to debug something.

Specifically, I'm currently trying to fix an error*, and was looking at the documentation re: STL documentation. 

- On https://jasonroelofs.com/rice/4.x/stl/stl.html#stl-class-names, in the code at the bottom the symbol is mentioned as `StringDoubelPair`
- On that page, https://jasonroelofs.com/rice/4.x/stl/vector.html, along with -- I imagine -- others**, you repeatedly typo the C++ template, omitting a close angle bracket `>`. (A scourge of C++ devs. :stuck_out_tongue: )

I know these are minor, but the last one at least made me actually try making this (albeit illogical) change on the off chance it would fix my problem.

Thanks again!

-------
*\** Off topic (and no pressure), but here it is if you have any immediate ideas. (I haven't given up on figuring it out myself yet, so not making another ticket for it just yet.)
  ```
  terminate called after throwing an instance of 'std::invalid_argument'
what():  Type is not defined with Rice: std::vector<SimpleBLE::Adapter, std::allocator<SimpleBLE::Adapter> >
  Aborted (core dumped)
  ```
*\*\**  Looks like just typoed it once and that happened to be in markup you reused elsewhere as a template.

**Comment by jasonroelofs** [comment]
Ah, sure enough, thanks for pointing these out, I will get them fixed.

As for your error, that often comes from trying to use a type conversion before it's defined. Order of operations gets important here. However hard to say more without seeing the code in question, if that's possible.

**Comment by mvastola** [comment]
I figured out the error. It was dumb. I forgot to include `rice/stl.hpp`, which was dumb, but I guess there isn't a good way to alert about that error.

Having another issue with callbacks/segfaults right now, which will be fun to debug :upside_down_face: . Might have questions at some point.

If you're interested, just put up what I've done at https://github.com/mvastola/SimpleRbBLE. I'm really excited by how little code it took to get this working to the extent that it is. Not stable or anything, but much further than I had hoped for for the time I put in.

**Comment by mvastola** [comment]
Oh, (let me know if I should make an issue for this): I'm not sure why, but there seems to be an issue with the published gem (forcing me to use git): `lib/rice.rb` seems to be missing from the version installed by `gem`/`bundle`.

Just in case you weren't aware.

**Comment by jasonroelofs** [comment]
These fixes have been applied. Thanks!
