### ISSUE TITLE
Missing Complex#is_convertible method

### ISSUE THREAD

**Issue by patleb** [jasonroelofs/rice#190]
The std::complex is missing the `is_convertible` method and it seems that there is no default method available either.

**Comment by jasonroelofs** [comment]
The wrapping of `std::complex` wasn't intended to be comprehensive, but a way to easily move from C++ to Ruby land (Ruby's built-in Complex class). What's the use case with `is_convertible` that's missing here?

**Comment by patleb** [comment]
Ok, I get it, thanks.

I was building a vector of `std::variant` with a complex in it. To make it work, I had to add:

```c++
    bool is_convertible(VALUE value)
    {
      return rb_type(value) == RUBY_T_COMPLEX;
    }
```

Also, the variant `class To_Ruby<std::variant<Types...>&>` conversion methods aren't compatible with `std::vector`. For example, it should be:

```c++
static VALUE convertElement(const std::variant<Types...>& data, bool takeOwnership)
```
instead of
```c++
static VALUE convertElement(std::variant<Types...>& data, bool takeOwnership)
```

**Comment by jasonroelofs** [comment]
Thanks for the report! I have fixed the nesting of `std::complex` and `std::vector` inside of `std::variant`. I was not able to trigger errors around `convertElement` though. Do you have an example setup that's causing you a compiler error?

**Comment by patleb** [comment]
It's been a while, I don't have an example at hand, but you could pass a const reference and that will trigger a compiler error. Is there a reason why you would want to mutate the data passed to `convertElement`? I took a look at the `convert` calls inside and they don't mutate the data... I'm a bit confused by the missing `const` keyword.

**Comment by patleb** [comment]
Yes, that's pretty good, thanks a lot!
