### ISSUE TITLE
convert std::vector<Test*> to ruby

### ISSUE THREAD

**Issue by pradip-shinde** [jasonroelofs/rice#192]
Hi
I am having a usecase to return vector (or STL container) holding pointers i.e std::vector<Test*> to ruby
here Test is my user defined class.
I got stuck to do this is this possible in rice? and how to do this

**Comment by jasonroelofs** [comment]
Yes this should be possible. You'll need to make sure `Test` is wrapped in Rice so the library knows how to handle elements of the `std::vector`. Was there a specific error you were running into here?

**Comment by pradip-shinde** [comment]
rice/rice/detail/../Data_Object.ipp:267:58: error: invalid initialization of reference of type 'Test*&' from expression of type 'Test'
  267 |         return *Data_Object<Intrinsic_T>::from_ruby(value);
      |                                                          ^


this error i am getting

**Comment by pradip-shinde** [comment]
> Yes this should be possible. You'll need to make sure `Test` is wrapped in Rice so the library knows how to handle elements of the `std::vector`. Was there a specific error you were running into here?

**Comment by pradip-shinde** [comment]
this is closed by mistake can you help on this

**Comment by jasonroelofs** [comment]
Can you link to / share the code you're trying to compile?

**Comment by pradip-shinde** [comment]
Rice Wrapper:

#include <rice/rice.hpp>
#include "stl/vector.hpp"

#include "Test.h"
#include "stl.hpp"


using namespace Rice;

extern "C"
void Init_DataModelWrapper() {
    Class rb_Student = define_class<Student>("Student");
    Class rb_Test = define_class<Test>("Test");
    //rb_Test.define_constructor(Constructor<Test>());
    rb_Test.define_method("addStudent", &Test::addStudent );
    rb_Test.define_method("getStudents", &Test::getStudents);
}


//C++ Code
Test.h

#include <rice/rice.hpp>
#include "stl/vector.hpp"

#include "Test.h"
#include "stl.hpp"


using namespace Rice;

extern "C"
void Init_DataModelWrapper() {
    Class rb_Student = define_class<Student>("Student");
    Class rb_Test = define_class<Test>("Test");
    //rb_Test.define_constructor(Constructor<Test>());
    rb_Test.define_method("addStudent", &Test::addStudent );
    rb_Test.define_method("getStudents", &Test::getStudents);
}

//
Test.cpp
#include "Test.h"

Test::Test() {

}

Test::~Test() {

}

void Test::addStudent(std::string sName, std::string sClass, int iAge) {
    Student* pStudent = new Student(sName, sClass, iAge);
    m_vectStudents.push_back(pStudent);
}

**Comment by jasonroelofs** [comment]
I can reproduce the compiler error, though I'm not sure how to fix it. If anything I'd recommend trying to use `std::shared_ptr` or `std::unique_ptr` instead of raw pointers. Those should work fine with Rice.

**Comment by pradip-shinde** [comment]
yes i have tried for std:shared_ptr its working, but there is one issue with shared ptr
when we iterate code in ruby first iteration its working fine, but for second iteration on same object its getting crash to access memeber function.
i have fixed this issue, in the constructor of shared pointer wrapper instead of std:move it should only copy the pointer rather thans transfering the ownership

**Comment by cfis** [comment]
Oh that is a good point. @pradip-shinde  I assume you mean this line of code:

https://github.com/jasonroelofs/rice/blob/549c37f8771d72262247c5a2aa3200fe5a6ce07f/rice/stl/smart_ptr.ipp#L12

That sure looks wrong to me :(

**Comment by cfis** [comment]
Will deal with the std::move on shared_pointers separately.
