### ISSUE TITLE
Version 4.3 Release

### ISSUE THREAD

**Issue by cfis** [jasonroelofs/rice#204]
@jasonroelofs tests are now passing. I updated the release notes and added docs for std::string_view. So ready for a 4.3.0 release (or I suppose it could be 4.2.2, either way).

I can go ahead and do a release if you want.

**Comment by jasonroelofs** [comment]
Making it 4.3.0 is fine. One PR jumped in today that looked good so including it. We should be good to go here, feel free to push a release up and I can get the docs updated.

I've also made the ruby-rice org and I'll get working on moving some things over there.

**Comment by cfis** [comment]
Done.

**Comment by jasonroelofs** [comment]
Thanks!

**Comment by jasonroelofs** [comment]
Docs are also updated.
