### ISSUE TITLE
SIGSEGV if initialize is redefined in Ruby

### ISSUE THREAD

**Issue by Lykos** [jasonroelofs/rice#43]
I found a minor, but very uncomfortable problem: If I define a class C using Rice, then the alloc function just returns a Null Pointer and the initialize function really allocates the object. But if the Ruby user redefines the initialize method of C, then the pointer stays a Null Pointer and the next method call is likely to cause a SIGSEGV.

Before I switched to rice recently, I used the C API for my library and there the solution was easy: In allocate, I allocate a struct with a Null pointer and an "initialized" flag which is initially set to false and in the initialize function, the real object is allocated and the flag is set to true. Instead of defining methods directly, I passed the function pointer to a wrapper function which checks this initialized flag and calls the wrapped function or throws a Ruby exception.

Redefining the "initialize" method of classes of an extension is a bad thing, but I still don't want my user to get segfaults since this may happen for example if the User accitentally passes the ,wrong class to some meta programming trick function which redefines initialize, so I propose that either you also solve this problem in the library or you document a clean way to achieve this safety.

**Comment by jasonroelofs** [comment]
I have looked at solving this problem periodically and each time come back with nothing that really fits with how Rice is structured. I'll update the documentation and leave this ticket open as documentation of this error case.

**Comment by cfis** [comment]
This isn't a solvable problem the way Ruby's C API works. The allocation function only takes one argument, the class, so construction cannot happen there. And there isn't a way to stop someone from overriding the initialize method. So going to close this issue.
