### ISSUE TITLE
confidence tests don't use overridden compiler

### ISSUE THREAD

**Issue by zsalzbank** [jasonroelofs/rice#72]
Some of my C++ code uses new features of C++11 that the default version of g++ doesn't include.  When I try to use `have_library` it would always fail because the new features weren't available and I would get linking errors.

I think this is because of these lines: https://github.com/jasonroelofs/rice/blob/master/ruby/lib/mkmf-rice.rb.in#L58-60.  The `$(CC)`  gets expanded too early, so that overridden globals aren't used.

What I ended up doing was something like this:

```ruby
require 'mkmf-rice'
original_cxx = $CXX
$CXX = 'g++-4.8'
TRY_LINK.sub!(original_cxx, $CXX)
```

Not sure what an elegant solution to this may be, but thought I'd mention it.

Thanks

**Comment by jasonroelofs** [comment]
So I think the best solution here is to set your `$CXX` values before you `require "mkmf-rice"`, which should work with no issues. I'll update documentation to mention this.
