### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Kagetsuki** [jasonroelofs/rice#74]
I'm working on the [rapngasm](https://github.com/apngasm/rapngasm) project and we're having some bizarre memory leak issues. So far we've confirmed:

* The C++ library apngasm is NOT leaking. We've valgrinded and profiled the hell out of it.
* The destructor is being called. The destructor is releasing the memory used internally by apngasm.
* Forcing GC after the Ruby object has gone out of scope or has been set to nil reduces the ammount of memory leaked dramatically. That's fine but it does not completely fix the leak.

And this is what tipped us off it may be Rice internal:
* We cored out a method (add_frame_file) so it doesn't actually save anything or allocate any memory and just returns. Only a string and two ints are passed. Then we ran this method and only this method 20k times in a loop and it still leaked.

Perhaps there's something wrong with how we wrote something [here](https://github.com/apngasm/rapngasm/blob/master/ext/rapngasm/rapngasm.cpp)? Is there something we can do to try and analyze this? Any help would be greatly appreciated!

**Comment by jasonroelofs** [comment]
Have you made any further progress here? I've been doing some research into `std::string` usage and while I haven't yet thrown together any explicit test scripts yet, it looks like the `from_ruby<std::string>` implementation in Rice proper is correct and shouldn't leak anything. However, I've seen reports that using `std::string&` can allow a leak to occur, and if you're triggering `from_ruby<std::string*>` instead and not deleting the string after use, that can also be a leak.

**Comment by Kagetsuki** [comment]
@jasonroelofs You are exactly correct, it's from passing strings with & and perhaps how we are passing bitmap data. On top of that I think there was some issue either with Ruby 2.1 or with pre 0.7 rice - after upping to 2.2 and 0.7 the memory allocation issue has dramatically reduced in size (but is still present - but thanks to your tip I think we know what to look at).

I'm closing this issue because it's basically "fixable" (I think) once we get around to it. Thanks for the help and sorry for the trouble!

* perhaps add a warning in the documentation about passing/returning data as pointers/references?

**Comment by jasonroelofs** [comment]
Cool, glad we could figure that one out. Documenting potential memory pitfalls isn't a bad idea, I'll look at putting something together.
