### ISSUE TITLE
Install fails for Ruby 2.2.0 (Mac OS X 10.10)

### ISSUE THREAD

**Issue by sickp** [jasonroelofs/rice#77]
Attempting to `gem install rice` with Ruby 2.2.0 results in these errors:

```
In file included from Struct.cpp:1:
In file included from ./Struct.hpp:5:
./Hash.hpp:25:27: error: unknown type name 'RHash'; did you mean 'Hash'?
  : public Builtin_Object<RHash, T_HASH>
                          ^~~~~
                          Hash
./Hash.hpp:24:7: note: 'Hash' declared here
class Hash
      ^
In file included from Struct.cpp:1:
In file included from ./Struct.hpp:5:
In file included from ./Hash.hpp:224:
./Hash.ipp:13:20: error: unknown type name 'RHash'; did you mean 'Hash'?
  : Builtin_Object<RHash, T_HASH>(protect(rb_hash_new))
                   ^~~~~
                   Hash
./Hash.hpp:24:7: note: 'Hash' declared here
class Hash
      ^
In file included from Struct.cpp:1:
In file included from ./Struct.hpp:5:
In file included from ./Hash.hpp:224:
./Hash.ipp:19:20: error: unknown type name 'RHash'; did you mean 'Hash'?
  : Builtin_Object<RHash, T_HASH>(v)
                   ^~~~~
                   Hash
./Hash.hpp:24:7: note: 'Hash' declared here
class Hash
      ^
In file included from Struct.cpp:1:
In file included from ./Struct.hpp:5:
In file included from ./Hash.hpp:224:
./Hash.ipp:295:26: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
  return iterator(*this, size());
         ~~~~~~~~        ^~~~~~
./Hash.ipp:301:32: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
  return const_iterator(*this, size());
         ~~~~~~~~~~~~~~        ^~~~~~
2 warnings and 3 errors generated.
make[2]: *** [Struct.o] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.1
BuildVersion:	14B25
```

```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

Cheers!

**Comment by jasonroelofs** [comment]
Thanks for the heads up, I'll see what I can figure out.

**Comment by jasonroelofs** [comment]
Simple reason, Ruby removed RHash from public includes:

https://bugs.ruby-lang.org/issues/9889

I think I've got a solution though, where I don't have to use these internal Ruby structs at all. Should have a fix to test out soon.

**Comment by jasonroelofs** [comment]
I've pushed a fix for this. Please give it a try and let me know if you run into any issues.

**Comment by sickp** [comment]
Thank you. I ran into a different issue trying to install the latest version from git.

**Comment by sickp** [comment]
This appears to be working fine. I needed to build and install the gem locally (using a fake version number) as another gem with a Rice dependency kept picking up 1.6.3 and not the github version. However, I believe that is a Bundler issue, and will be resolved once Rice has another official gem release.

**Comment by jasonroelofs** [comment]
Right, I haven't done a version bump yet. Due to the changes which could possibly break code of someone making use of Ruby internals, I will probably release this as 1.7.

What's the other dependency that's using Rice?

**Comment by sickp** [comment]
https://github.com/elliotlaster/Ruby-Diff-Match-Patch

**Comment by qhwa** [comment]
+1 Works fine for me.

We are going to use ruby 2.2.0, however, some gems depend on rice.
Waiting for the 1.7 to be released.
If that takes long, I suggest bumping to a pre-release version first.

**Comment by jasonroelofs** [comment]
1.7 has been released. Thanks for your help!
