### ISSUE TITLE
Invalid pointer returned at to_from_ruby.ipp:264

### ISSUE THREAD

**Issue by noseka1** [jasonroelofs/rice#79]
Code excerpt from to_from_ruby.ipp:264

template<>
inline
char const * from_ruby<char const *>(Rice::Object x)
{
  return Rice::String(x).str().data();
}

Rice::String(x).str() creates a temporary std::string object. This object is destroyed. The function from_ruby returns a pointer to already freed memory.

**Comment by jasonroelofs** [comment]
Are you experiencing a crash due to this? It's definitely not covered in the test suite. I'll take a look and see how better to support this conversion.

**Comment by noseka1** [comment]
No, it doesn't crash for me. I stumbled upon the issue whe using Address Sanitizer tool http://clang.llvm.org/docs/AddressSanitizer.html to debug my own library.

I'm also wondering who is supposed to delete the pointer returned from this from_ruby function. At the first glance I couldn't see the a delete function called somewhere in the rice code.

**Comment by jasonroelofs** [comment]
If LLVM says this isn't great then that's probably true but I'm not sure how best to go about fixing this. I haven't been able to trigger a crash or any corruption. On top of that I don't think this method is used much, if at all, so for now I'm just going to leave it as it is.
