### ISSUE TITLE
Help on a Ruby extension C++ exception failure on Solaris

### ISSUE THREAD

**Issue by sodabrew** [jasonroelofs/rice#82]
Hi! I'm debugging eventmachine/eventmachine#376 and I wonder if you've run into a situation where Ruby explodes in the presence of `try { throw std::runtime_error ("foo"); } catch (std::runtime_error e) { it crashes before getting here. }`

**Comment by jasonroelofs** [comment]
I've never seen such a situation. From reading the bug, I have to imagine there's something wrong with Solaris GCC that would make such code not work properly.

**Comment by sodabrew** [comment]
I installed GCC 4.8 on my test VM. If the Ruby I'm using was built with GCC 4.5 (another version available in Solaris pkg repo) have they changed the stack format along the 4.x series?

**Comment by jasonroelofs** [comment]
I really don't know anything else, sorry. It's definitely a weird error.
