### ISSUE TITLE
passing reference to constructor 

### ISSUE THREAD

**Issue by Raven24** [jasonroelofs/rice#85]
hi,
I'm using a C++ class that wants a char** array passed to it by reference it in the constructor (the class then potentially changes the data in the array, but I don't need that array again).
I would like to pass the data via Ruby as an array of strings, copy it in a `from_ruby` conversion and just have it passed by reference to the class constructor.
Is that possible at all, somehow? Could I wrap the constructor in a certain way?

**Comment by jasonroelofs** [comment]
I'm having a hard time following exactly what you're trying to do. Do you have a link or could you paste the code that you're trying to wrap with Rice?

**Comment by Raven24** [comment]
This is a simplified example of what I'm trying to do:
(Just FYI, I'm not really a person who writes compiled code, that's why I'd like to bridge over to Ruby...)

```c++
// c++ constructor code
MainApplication::MainApplication(int &argc, char **argv)
  : arg_count(argc), arg_vals(argv)
{
  // ...
}

// basically, MainApp provides initialization and a few nice wrapper methods, 
// if you pass argc/argv to it. this is just to illustrate.
std::vector<std:string> MainApplication::arguments()
{
  std::vector<std::string> vec;
  for(int a=0; a < arg_count; ++a) {
    vec.push_back(std::string(arg_vals[a]));
  }
  return vec;
}
```

```c++
// my Rice code

template<>
char** from_ruby< char** > (Object o) {
  Array a(o);
  char ** v = new char*[a.size()];
  for(Array::iterator aI = a.begin(); aI != a.end(); ++aI) {
    size_t i = aI.index();
    String s = (String) *aI;
    v[i] = new char[s.length() + 1];
    strcpy(v[i], s.c_str());
  }
  return v;
}

template<>
Object to_ruby< std::vector<std::string> >(const std::vector<std::string> &list) {
  Array a;
  for(std::vector<std::string>::const_iterator i = list.begin(); i != list.end(); i++) {
    const char* str(*i);
    a.push(new String(str));
  }
  return a;
}

extern "C"
void Init_test() {
  // ...
  define_class<MainApplication>("MainApplication")
    .define_constructor(Constructor<MainApplication, int, char**>())
    .define_method("arguments", &MainApplication::arguments);
  // ...
}
```

```ruby
# my ruby code
require "test"

app = MainApplication.new(ARGV.size, ARGV)

# here I would get an empty array
puts app.arguments
```

**Comment by jasonroelofs** [comment]
My first inclination is that this pattern probably isn't the best way to utilize Rice or any Ruby<->C++ communication. Ruby should handle command line parsing and `ARGV`. Could you instead take ARGV from Ruby directly and pass in just the options you need to set according to the command line options set.

Could you explain more what this app / library is supposed to do?

**Comment by Raven24** [comment]
I'm trying to write a binding to an existing Qt program.
The apps main class extends [QApplication](http://doc.qt.io/qt-5/qapplication.html) which (unfortunately) can only be constructed using that signature. Also the variables must not be deleted for the entire lifetime of the application...
I know this is probably not the way Rice is intended to be used, but I'd hoped it would at least be possible some way.

**Comment by jasonroelofs** [comment]
I'm sure it's possible but it probably isn't going to be easy. Maybe there's another direction to implement what you're trying to accomplish? Why do you want to start a QT application from Ruby like this?
