### ISSUE TITLE
README in MD format

### ISSUE THREAD

**Issue by Kagetsuki** [jasonroelofs/rice#90]
Very minor issue, but I think it would be wise to distribute a README.md as well. There is an easy way to generate MD from XML, but unfortunately enabling XML generation in doxygen.ac doesn't actually seem to generate any XML. If I can get a little direction on how to generate a README.xml I'll generate a README.md from it.

**Comment by jasonroelofs** [comment]
While I'm not against Markdown and I always use it by default for any new library or app I build, it hasn't made sense to make the change here as that would require completely rebuilding how Rice's documentation is generated, and the time hasn't seemed worth the effort. What do you feel is the benefit of switching to Markdown?

**Comment by Kagetsuki** [comment]
It just seems a more logical format to display the bundled README in. Actually, is README even converted in anything? I didn't immediately see it in any generated documentation.

Other than a slight improvement in readability I don't see any benefit. If it is in fact being used in generated documents then throwing in some sort of conversion would likely, as you note, not be worth the effort. Feel free to close the issue.

**Comment by jasonroelofs** [comment]
The README becomes the main page of http://jasonroelofs.github.io/rice/ via Doxygen.

**Comment by Kagetsuki** [comment]
Got it. I'm sure we could re-tool it to generate from MD, but at this point I doubt it's worth the effort. Closing issue.
