### ISSUE TITLE
Compile error with Ruby 2.3.0 and gcc 4.9.2

### ISSUE THREAD

**Issue by lyro** [jasonroelofs/rice#91]
I get the following error when installing rice with ruby 2.3.0 and g++ 4.9.2:

```
g++ -DHAVE_CONFIG_H -I.  -I/home/fifr/.rbenv/versions/2.3.0/include/ruby-2.3.0 -I/home/fifr/.rbenv/versions/2.3.0/include/ruby-2.3.0/x86_64-linux -I/home/fifr/.rbenv/versions/2.3.0/include/ruby-
2.3.0/x86_64-linux  -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-string
s -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  -fPIC -fPIC -I/home/fifr/.rbenv/versions/2.3.0/include/ruby-2.3.0 -I/home/f
ifr/.rbenv/versions/2.3.0/include/ruby-2.3.0/x86_64-linux -I/home/fifr/.rbenv/versions/2.3.0/include/ruby-2.3.0/x86_64-linux -MT Module.o -MD -MP -MF $depbase.Tpo -c -o Module.o Module.cpp &&\
mv -f $depbase.Tpo $depbase.Po
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++
In file included from Array.hpp:217:0,
                 from Module.cpp:4:
Array.ipp: In member function ‘Rice::Object Rice::Array::operator[](ptrdiff_t) const’:
Array.ipp:55:173: error: ‘__builtin_choose_expr’ was not declared in this scope
   VALUE * ptr = RARRAY_PTR(this->value());
                                                                                                                                                                             ^
Array.ipp: In member function ‘VALUE* Rice::Array::to_c_array()’:
Array.ipp:94:166: error: ‘__builtin_choose_expr’ was not declared in this scope
   return RARRAY_PTR(this->value());
```
I do not get that error with ruby 2.2.4, so maybe something changed? Are some special compile flags required?

**Comment by jasonroelofs** [comment]
I haven't gotten around to building against 2.3.0 yet. Will definitely take a look.

**Comment by lyro** [comment]
Sure, take your time ;)

Am 26. Dezember 2015 18:32:38 MEZ, schrieb Jason Roelofs <notifications@github.com>:

**Comment by jasonroelofs** [comment]
Looks like we have the same problem as here: https://github.com/robinst/taglib-ruby/pull/68

**Comment by jasonroelofs** [comment]
And specifically only with `g++`. `clang` on OSX (El Capitan) compiles and runs perfectly fine with 2.3.0.

**Comment by jasonroelofs** [comment]
I pushed some changes to master that should fix this problem. I haven't explicitly tested against `g++` yet, will get to that later, but if you have a chance let me know if this works for you.

**Comment by jasonroelofs** [comment]
Well Travis says that the compilation passes, but it segfaults, which I was half expecting to happen. I'll need to figure out how better to implement `Rice::Array::to_c_array`, or otherwise replace that functionality.

**Comment by lyro** [comment]
Hm, with your changes rice compiles. But is the new implementation of `Rice::Array::to_c_array` correct? Unless I'm wrong, the pointer returned by this function is a pointer to a temporary object `std::vector<VALUE> arr`, so it's probably dangling (and this might cause the segfault).

**Comment by lyro** [comment]
Actually, I think the problem is explained in gcc docs https://gcc.gnu.org/onlinedocs/gcc-5.3.0/gcc/Other-Builtins.html#Other-Builtins

The section about `__builtin_choose_expr` states

     Note: This construct is only available for C. 

The problem is that `RARRAY_PTR` is now implemented in terms of this builtin. There are two workarounds: implement `__builtin_choose_expr` on your own or wrap the call to `RARRAY_PTR` in a C function (the latter is probably more robust).

**Comment by jasonroelofs** [comment]
Yeah, I'm actually surprised that my impl of `to_c_array` didn't crash with clang, and admittedly I've been outside the C++ loop for a long time so I'm not sure what the right way is of doing what I need to do, but I'll keep digging.

**Comment by jasonroelofs** [comment]
Specifically, I don't want to rely on `RARRAY_PTR` anymore as that's diving into the implementation details of a Ruby array, which has changed before and will change in the future.  I have also contemplated removing that method entirely and updating the one place internally that uses it (`Rice::Object::vcall` to build the array itself).

**Comment by lyro** [comment]
This sounds like a good idea to me ;)

**Comment by jasonroelofs** [comment]
Went ahead with that. `to_c_array` is gone. Tests pass fine on Travis. Please give master a shot.

**Comment by lyro** [comment]
Works nicely, thanks.

**Comment by jasonroelofs** [comment]
Pushed a 2.1.0 release with these changes. Thanks for the report and help!
