### ISSUE TITLE
std=c++11 and auto_ptr

### ISSUE THREAD

**Issue by kugel-** [jasonroelofs/rice#93]
When building under g++ with -std=c++11 there are lots of warnings 

`/var/lib/gems/2.3.0/gems/rice-2.1.0/ruby/lib/include/rice/detail/../Data_Type_defn.hpp:207:15: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]`

I believe the final standard has only unique_ptr, instead of auto_ptr. Can rice be fixed to not use auto_ptr?

**Comment by jasonroelofs** [comment]
I can definitely take a look and making that conversion.

**Comment by jasonroelofs** [comment]
I've been looking into this and found a few things:

* I already did this change a while ago, but used a copied version of the autoconf macro to see if C++11 is supported
* I've been able to reproduce these warnings, but not reliably

I've updated master to use the official macros (you may need to install `autoconf-archive` to get access to them). Could you try out the master branch and see if you still get these warnings?

Thanks.

**Comment by cfis** [comment]
I think this is resolved by 25d820fa1daf46fdaad3d223c51382cbcba79ef1.
