### ISSUE TITLE
Enum value to RUBY

### ISSUE THREAD

**Issue by jbibollet** [jasonroelofs/rice#94]
I'm trying to wrap an Enum type from C++ to RUBY using the `Rice::Enum` functionality; this works great to go from RUBY to C++, but not the other way around:  below is a sample code exposing the issue (it's pretty much the same as the Enum example provided), to which I added two functions `fn1` and `fn2` respectively receiving an Enum value from RUBY and returning an Enum value to RUBY:

```c++
namespace
{
enum Sample_Enum
{
    SE_FOO = 1,
    SE_BAR = 42,
    SE_BAZ = 100,
};
} // namespace

Rice::Enum<Sample_Enum> sample_enum_type;

template<>
Sample_Enum from_ruby<Sample_Enum>(Rice::Object x)
{
    Rice::Data_Object<Sample_Enum> d(x, sample_enum_type);
    return *d;
}

void
fn1(Sample_Enum value)
{
    std::cout << "Called with : " << value << std::endl;
}

Sample_Enum
fn2(void)
{
    return SE_BAR;
}

extern "C"
void Init_Enum()
{
    sample_enum_type = Rice::define_enum<Sample_Enum>("Sample_Enum")
        .define_value("FOO", SE_FOO)
        .define_value("BAR", SE_BAR)
        .define_value("BAZ", SE_BAZ);

    Rice::define_class("Test")
        .define_method("fn1", &fn1)
        .define_method("fn2", &fn2);
}
```

When executing the below ruby code:
```ruby
Test.new.fn1(Sample_Enum::BAZ)
puts Test.new.fn2
```

The output is:
```shell
Called with : 100
INVALID(42)
```

> Note the **INVALID** (coming from the `to_s` method, despite having the right integer value).

Now, if in my C++ code I add the following code:
```c++

template<>
Rice::Object
to_ruby<Sample_Enum>(const Sample_Enum& obj)
{
#define CASE(X)  case SE_ ## X: return rb_const_get_at(sample_enum_type, rb_intern(#X))
    switch (obj) {
        CASE(FOO);
        CASE(BAR);
        CASE(BAZ);
    }
#undef CASE
}
```

I get the expected output:
```shell
Called with : 100
BAR
```

- Should `Rice::Enum` provide a `to_ruby` that would allow better and 'out of the box' usage of Enums ?

**Comment by jasonroelofs** [comment]
There is definitely a bug here. I'll dive in and see what I can come up with. Thanks for the detailed report!

**Comment by jasonroelofs** [comment]
It looks like the bug is only in the `to_s` output. From my testing, Rice is returning a `Sample_Enum::BAR` from `fn2`. If you run your code as:

```ruby
puts Test.new.fn2.class
```

you should see `Sample_Enum`. I will get the inspect output confusion fixed up.

**Comment by jasonroelofs** [comment]
This issue should be fixed. Please give `master` a shot and I plan on cutting a release when RVM and Travis get Ruby 2.4 up and running sometime this week or the next.

**Comment by jbibollet** [comment]
Thanks a lot for the quick fix @jasonroelofs, I can confirm your commit fixes this issue.

**Comment by jasonroelofs** [comment]
As there seem to be some issues with Ruby 2.4 I'm not going to wait any longer. I've pushed Rice 2.1.1 with these fixes. Thanks again for your report!
