### ISSUE TITLE
Example of unmanaged object

### ISSUE THREAD

**Issue by ryannevell** [jasonroelofs/rice#96]
Is there any example provided for creating a Ruby object from a C++ object but without giving ownership to Ruby? I am wrapping an existing library which exposes raw pointers to C++ objects, but retains ownership and does not expect the caller to delete them. Relying on the default to_ruby for this class works fine until the Ruby object gets garbage collected and frees the underlying object.

I was expecting something similar to undef_creation_funcs, ie undef_free_func, but didn't see anything like that.

Thank you

**Comment by jasonroelofs** [comment]
What you want to do in this situation is to provide a custom `mark` function on the Ruby wrapper that will mark the object during the GC sweep, preventing it from getting removed.  There are a couple of ways of doing this. Could you post more details on who owns this Ruby object and how you use it?

**Comment by ryannevell** [comment]
I'm not sure that overriding the `mark` function is right in this case - The Ruby wrapper is really just a temporary handle, so I would want it to get reclaimed if nobody on the Ruby side was using it anymore. I've had success by providing a custom `free` function instead. This allows the wrapper to be reclaimed, but doesn't attempt to delete the underlying object which my code doesn't own.

While this works, it is quite tedious. For each class I'm writing:
```
  template <>
  Rice::Object to_ruby<SomeClass*>(SomeClass* const &x)
  {
    if (!x) return Rice::Nil;
    return Rice::Data_Object<SomeClass>(x, rb_cSomeClass, nullptr, nullptr);
  }     
```

However, after getting further along this path, I've realized that I want to be able to test for object identity equivalence (.equal?). So I need to instrument a mechanism for returning the same Data_Object instance, if one already exists on the Ruby side. So I'm going to need a custom `free` function anyways to remove my Objects from this mechanism.

**Comment by jasonroelofs** [comment]
Ah, ok that makes sense then. Yeah I don't have a good alternative solution here vs what you've already come up with.
