### ISSUE TITLE
Is there any plan to support lambda expression for define_method?

### ISSUE THREAD

**Issue by kou** [jasonroelofs/rice#99]
What do you think about the following API?

```cpp
#include <rice/Class.hpp>

using namespace Rice;

extern "C"
void Init_test()
{
  Class rb_cTest = define_class("Test");
  rb_cTest.define_method("hello", [](Object self) -> Object {
    return String("hello");
  });
}
```

It looks like the following Ruby script:

```ruby

class Test
  define_method(:hello) do
    "hello"
  end
end
```

Background:

Ruby like API for defining a method may be useful for improving performance by creating an extension in C++. Because it'll be easy to use API for Rubyists.

There is https://github.com/v0dro/rubex approach. It extends Ruby syntax and generates Ruby and C from the extended Ruby syntax. (Cython like approach.)

I like the approach that uses C++ directly than approach that extends Ruby syntax because we don't need to learn/improve/maintain our original syntax (extended Ruby syntax). I like learning only existing languages (Ruby and C++). Because existing languages will be improved. We can write extensions easily when they are improved.

**Comment by jasonroelofs** [comment]
That's definitely an interesting idea. I wonder if similar such syntax may already work as that should be just a function pointer. Some Googling shows me that you can make a function pointer to a lambda only if that lambda doesn't capture (http://stackoverflow.com/questions/28746744/passing-lambda-as-function-pointer) so such a syntax would probably need explicit handling in Rice itself.

In terms of planning for features, Rice is effectively in maintenance-only mode at this point as I don't use it but I'm happy to help keep things running. If you'd like to try your hand at adding such functionality I'm here to answer questions and to point you in the right direction!

**Comment by kou** [comment]
Thanks for sharing the current Rice status.
I may try to implement this feature.

**Comment by ankane** [comment]
fwiw, it works as a pointer - thanks @jasonroelofs

```cpp
rb_cTest.define_method("hello", *[](Object self) -> Object {
  return String("hello");
});
```

**Comment by jasonroelofs** [comment]
Hey, that's slick! Definitely something to be added to the documentation then.

**Comment by cfis** [comment]
I've added full support for lambdas to my branch - not just pointers to lambdas. 

Thus this works:

```cpp
rb_cTest.define_method("hello", [](Object self) 
{
  return String("hello");
})
```
It also works for singleton methods and global functions.

**Comment by cfis** [comment]
Closing this now that lambdas are fully supported.

**Comment by tim37021** [comment]
@jasonroelofs 
Hi, is it possible to get the c++ instance from `Rice::Object self` with this lambda syntax?

**Comment by cfis** [comment]
Depends on the type of object being wrapped. But generally use * or ->. There is also a get method on DataObject.

See:

https://github.com/jasonroelofs/rice/blob/a7592534a0af4c970926bcf44711b0865fb5fd5e/rice/Data_Object.ipp#L55
